#pragma once

// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include <QObject>
#include <test1>

namespace Conf {

class Preferences : public QObject {
Q_OBJECT

public:
	Preferences(QObject *parent = 0);
};

}
