// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include "test-simple-prefs-default-value.h"
#include <QSettings>

Preferences::Preferences(QObject *parent) : QObject(parent),
	_name("tomaz"),
	_age(2)
{
}

QString Preferences::name() const
{
	return _name;
}

int Preferences::age() const
{
	return _age;
}

void Preferences::setName(const QString& value)
{
	if (_name==value) {
		return;
	}
	_name = value;
	Q_EMIT nameChanged(value);
}

void Preferences::setAge(int value)
{
	if (_age==value) {
		return;
	}
	_age = value;
	Q_EMIT ageChanged(value);
}

