#pragma once

// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include <QObject>
#include <QString>


class Preferences : public QObject {
Q_OBJECT
	Q_PROPERTY(QString name READ name WRITE setName NOTIFY nameChanged)
	Q_PROPERTY(int age READ age WRITE setAge NOTIFY ageChanged)

public:
	Preferences(QObject *parent = 0);
	QString name() const;
	QString nameDefault() const;
	int age() const;
	int ageDefault() const;

public:
	 Q_SLOT void setName(const QString& value);
	 Q_SLOT void setAge(int value);
	 Q_SIGNAL void nameChanged(const QString& value);
	 Q_SIGNAL void ageChanged(int value);

private:
	QString _name;
	int _age;
};

