#pragma once

// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include <functional>
#include <QObject>

#include <test1>


class Preferences : public QObject {
	Q_OBJECT

public:
	void sync();
	void load();
	static Preferences* self();
	 void loadDefaults();

private:
	Preferences(QObject *parent = 0);
};

