// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include "test-simple-inner-pref.h"
#include <QSettings>

Preferences::Preferences(QObject *parent) : QObject(parent)
{
}

