#pragma once

// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include <functional>
#include <QObject>

class InnerStruct : public QObject {
	Q_OBJECT

public:
	InnerStruct(QObject *parent = 0);
	 void loadDefaults();
};

class Preferences : public QObject {
	Q_OBJECT
Q_PROPERTY(QObject* inner_struct MEMBER _innerStruct CONSTANT)

public:
	void sync();
	void load();
	static Preferences* self();
	 void loadDefaults();
	InnerStruct *innerStruct() const;

private:
	InnerStruct *_innerStruct;
	Preferences(QObject *parent = 0);
};

