// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include "test-simple-inner-pref.h"
#include <QSettings>

InnerStruct::InnerStruct(QObject *parent) : QObject(parent)
{
}

void InnerStruct::loadDefaults()
{
}
Preferences::Preferences(QObject *parent) : QObject(parent),
	_innerStruct(new InnerStruct(this))
{
	load();
}

InnerStruct* Preferences::innerStruct() const
{
	return _innerStruct;
}

void Preferences::loadDefaults()
{
	_innerStruct->loadDefaults();
}
void Preferences::sync()
{
}

void Preferences::load()
{
}

Preferences* Preferences::self()
{
	static Preferences s;
	return &s;
}
