// DO NOT EDIT THIS FILE
// This file was automatically generated by configuration-parser
// There will be a .conf file somewhere which was used to generate this file
// See https://github.com/tcanabrava/configuration-parser

#include "test-simple-prefs-default-value.h"
#include <QSettings>

Preferences::Preferences(QObject *parent) : QObject(parent),
	_name("tomaz"),
	_age(2)
{
	load();
}

QString Preferences::name() const
{
	return _name;
}

int Preferences::age() const
{
	return _age;
}

void Preferences::setName(const QString& value)
{
	if (_name==value) {
		return;
	}
	if (nameRule && !nameRule(value)) {
		return;
	}
	_name = value;
	Q_EMIT nameChanged(value);
}

void Preferences::setAge(int value)
{
	if (_age==value) {
		return;
	}
	if (ageRule && !ageRule(value)) {
		return;
	}
	_age = value;
	Q_EMIT ageChanged(value);
}

void Preferences::setNameRule(std::function<bool(QString)> rule)
{
	nameRule = rule;
}

void Preferences::setAgeRule(std::function<bool(int)> rule)
{
	ageRule = rule;
}

QString Preferences::nameDefault() const
{
	return "tomaz";
}
int Preferences::ageDefault() const
{
	return 2;
}
void Preferences::loadDefaults()
{
	setName("tomaz");
	setAge(2);
}
void Preferences::sync()
{
	QSettings s;
	if (name() == nameDefault()){
		s.remove("name");
	} else { 
		s.setValue("name",name());
	}
	if (age() == ageDefault()){
		s.remove("age");
	} else { 
		s.setValue("age",age());
	}
}

void Preferences::load()
{
	QSettings s;
	setName(s.value("name", "tomaz").value<QString>());
	setAge(s.value("age", 2).value<int>());
}

Preferences* Preferences::self()
{
	static Preferences s;
	return &s;
}
